# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tx-signer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tx-signer.proto',
  package='PocketWalletQt',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ftx-signer.proto\x12\x0ePocketWalletQt\x1a\x19google/protobuf/any.proto\"\xa7\x01\n\nProtoStdTx\x12!\n\x03msg\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12!\n\x03\x66\x65\x65\x18\x02 \x03(\x0b\x32\x14.PocketWalletQt.Coin\x12\x34\n\tsignature\x18\x03 \x01(\x0b\x32!.PocketWalletQt.ProtoStdSignature\x12\x0c\n\x04memo\x18\x04 \x01(\t\x12\x0f\n\x07\x65ntropy\x18\x05 \x01(\x03\"9\n\x11ProtoStdSignature\x12\x11\n\tpublicKey\x18\x01 \x01(\x0c\x12\x11\n\tSignature\x18\x02 \x01(\x0c\"V\n\nStdSignDoc\x12\x0f\n\x07\x43hainID\x18\x01 \x01(\t\x12\x0b\n\x03\x66\x65\x65\x18\x02 \x01(\x0c\x12\x0c\n\x04memo\x18\x03 \x01(\t\x12\x0b\n\x03msg\x18\x04 \x01(\x0c\x12\x0f\n\x07\x65ntropy\x18\x05 \x01(\x03\"%\n\x04\x43oin\x12\r\n\x05\x64\x65nom\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\"(\n\x07\x44\x65\x63\x43oin\x12\r\n\x05\x64\x65nom\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\t\"?\n\rMsgProtoStake\x12\x0f\n\x07pub_key\x18\x01 \x01(\x0c\x12\x0e\n\x06\x63hains\x18\x02 \x03(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\"\n\x0fMsgBeginUnstake\x12\x0f\n\x07\x41\x64\x64ress\x18\x01 \x01(\x0c\"\x1c\n\tMsgUnjail\x12\x0f\n\x07\x41ppAddr\x18\x01 \x01(\x0c\"Y\n\x11MsgProtoNodeStake\x12\x11\n\tPublickey\x18\x01 \x01(\x0c\x12\x0e\n\x06\x43hains\x18\x02 \x03(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x12\n\nServiceUrl\x18\x04 \x01(\t\"&\n\x13MsgBeginNodeUnstake\x12\x0f\n\x07\x41\x64\x64ress\x18\x01 \x01(\x0c\"&\n\rMsgNodeUnjail\x12\x15\n\rValidatorAddr\x18\x01 \x01(\x0c\"A\n\x07MsgSend\x12\x13\n\x0b\x46romAddress\x18\x01 \x01(\x0c\x12\x11\n\tToAddress\x18\x02 \x01(\x0c\x12\x0e\n\x06\x61mount\x18\x03 \x01(\tb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_PROTOSTDTX = _descriptor.Descriptor(
  name='ProtoStdTx',
  full_name='PocketWalletQt.ProtoStdTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='PocketWalletQt.ProtoStdTx.msg', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fee', full_name='PocketWalletQt.ProtoStdTx.fee', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='PocketWalletQt.ProtoStdTx.signature', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memo', full_name='PocketWalletQt.ProtoStdTx.memo', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entropy', full_name='PocketWalletQt.ProtoStdTx.entropy', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=230,
)


_PROTOSTDSIGNATURE = _descriptor.Descriptor(
  name='ProtoStdSignature',
  full_name='PocketWalletQt.ProtoStdSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='publicKey', full_name='PocketWalletQt.ProtoStdSignature.publicKey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Signature', full_name='PocketWalletQt.ProtoStdSignature.Signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=232,
  serialized_end=289,
)


_STDSIGNDOC = _descriptor.Descriptor(
  name='StdSignDoc',
  full_name='PocketWalletQt.StdSignDoc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ChainID', full_name='PocketWalletQt.StdSignDoc.ChainID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fee', full_name='PocketWalletQt.StdSignDoc.fee', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memo', full_name='PocketWalletQt.StdSignDoc.memo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='PocketWalletQt.StdSignDoc.msg', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entropy', full_name='PocketWalletQt.StdSignDoc.entropy', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=377,
)


_COIN = _descriptor.Descriptor(
  name='Coin',
  full_name='PocketWalletQt.Coin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='denom', full_name='PocketWalletQt.Coin.denom', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='PocketWalletQt.Coin.amount', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=416,
)


_DECCOIN = _descriptor.Descriptor(
  name='DecCoin',
  full_name='PocketWalletQt.DecCoin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='denom', full_name='PocketWalletQt.DecCoin.denom', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='PocketWalletQt.DecCoin.amount', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=458,
)


_MSGPROTOSTAKE = _descriptor.Descriptor(
  name='MsgProtoStake',
  full_name='PocketWalletQt.MsgProtoStake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pub_key', full_name='PocketWalletQt.MsgProtoStake.pub_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chains', full_name='PocketWalletQt.MsgProtoStake.chains', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='PocketWalletQt.MsgProtoStake.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=460,
  serialized_end=523,
)


_MSGBEGINUNSTAKE = _descriptor.Descriptor(
  name='MsgBeginUnstake',
  full_name='PocketWalletQt.MsgBeginUnstake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Address', full_name='PocketWalletQt.MsgBeginUnstake.Address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=559,
)


_MSGUNJAIL = _descriptor.Descriptor(
  name='MsgUnjail',
  full_name='PocketWalletQt.MsgUnjail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='AppAddr', full_name='PocketWalletQt.MsgUnjail.AppAddr', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=589,
)


_MSGPROTONODESTAKE = _descriptor.Descriptor(
  name='MsgProtoNodeStake',
  full_name='PocketWalletQt.MsgProtoNodeStake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Publickey', full_name='PocketWalletQt.MsgProtoNodeStake.Publickey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Chains', full_name='PocketWalletQt.MsgProtoNodeStake.Chains', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='PocketWalletQt.MsgProtoNodeStake.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ServiceUrl', full_name='PocketWalletQt.MsgProtoNodeStake.ServiceUrl', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=591,
  serialized_end=680,
)


_MSGBEGINNODEUNSTAKE = _descriptor.Descriptor(
  name='MsgBeginNodeUnstake',
  full_name='PocketWalletQt.MsgBeginNodeUnstake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Address', full_name='PocketWalletQt.MsgBeginNodeUnstake.Address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=682,
  serialized_end=720,
)


_MSGNODEUNJAIL = _descriptor.Descriptor(
  name='MsgNodeUnjail',
  full_name='PocketWalletQt.MsgNodeUnjail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ValidatorAddr', full_name='PocketWalletQt.MsgNodeUnjail.ValidatorAddr', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=722,
  serialized_end=760,
)


_MSGSEND = _descriptor.Descriptor(
  name='MsgSend',
  full_name='PocketWalletQt.MsgSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='FromAddress', full_name='PocketWalletQt.MsgSend.FromAddress', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ToAddress', full_name='PocketWalletQt.MsgSend.ToAddress', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='PocketWalletQt.MsgSend.amount', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=762,
  serialized_end=827,
)

_PROTOSTDTX.fields_by_name['msg'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_PROTOSTDTX.fields_by_name['fee'].message_type = _COIN
_PROTOSTDTX.fields_by_name['signature'].message_type = _PROTOSTDSIGNATURE
DESCRIPTOR.message_types_by_name['ProtoStdTx'] = _PROTOSTDTX
DESCRIPTOR.message_types_by_name['ProtoStdSignature'] = _PROTOSTDSIGNATURE
DESCRIPTOR.message_types_by_name['StdSignDoc'] = _STDSIGNDOC
DESCRIPTOR.message_types_by_name['Coin'] = _COIN
DESCRIPTOR.message_types_by_name['DecCoin'] = _DECCOIN
DESCRIPTOR.message_types_by_name['MsgProtoStake'] = _MSGPROTOSTAKE
DESCRIPTOR.message_types_by_name['MsgBeginUnstake'] = _MSGBEGINUNSTAKE
DESCRIPTOR.message_types_by_name['MsgUnjail'] = _MSGUNJAIL
DESCRIPTOR.message_types_by_name['MsgProtoNodeStake'] = _MSGPROTONODESTAKE
DESCRIPTOR.message_types_by_name['MsgBeginNodeUnstake'] = _MSGBEGINNODEUNSTAKE
DESCRIPTOR.message_types_by_name['MsgNodeUnjail'] = _MSGNODEUNJAIL
DESCRIPTOR.message_types_by_name['MsgSend'] = _MSGSEND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoStdTx = _reflection.GeneratedProtocolMessageType('ProtoStdTx', (_message.Message,), {
  'DESCRIPTOR' : _PROTOSTDTX,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.ProtoStdTx)
  })
_sym_db.RegisterMessage(ProtoStdTx)

ProtoStdSignature = _reflection.GeneratedProtocolMessageType('ProtoStdSignature', (_message.Message,), {
  'DESCRIPTOR' : _PROTOSTDSIGNATURE,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.ProtoStdSignature)
  })
_sym_db.RegisterMessage(ProtoStdSignature)

StdSignDoc = _reflection.GeneratedProtocolMessageType('StdSignDoc', (_message.Message,), {
  'DESCRIPTOR' : _STDSIGNDOC,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.StdSignDoc)
  })
_sym_db.RegisterMessage(StdSignDoc)

Coin = _reflection.GeneratedProtocolMessageType('Coin', (_message.Message,), {
  'DESCRIPTOR' : _COIN,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.Coin)
  })
_sym_db.RegisterMessage(Coin)

DecCoin = _reflection.GeneratedProtocolMessageType('DecCoin', (_message.Message,), {
  'DESCRIPTOR' : _DECCOIN,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.DecCoin)
  })
_sym_db.RegisterMessage(DecCoin)

MsgProtoStake = _reflection.GeneratedProtocolMessageType('MsgProtoStake', (_message.Message,), {
  'DESCRIPTOR' : _MSGPROTOSTAKE,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.MsgProtoStake)
  })
_sym_db.RegisterMessage(MsgProtoStake)

MsgBeginUnstake = _reflection.GeneratedProtocolMessageType('MsgBeginUnstake', (_message.Message,), {
  'DESCRIPTOR' : _MSGBEGINUNSTAKE,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.MsgBeginUnstake)
  })
_sym_db.RegisterMessage(MsgBeginUnstake)

MsgUnjail = _reflection.GeneratedProtocolMessageType('MsgUnjail', (_message.Message,), {
  'DESCRIPTOR' : _MSGUNJAIL,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.MsgUnjail)
  })
_sym_db.RegisterMessage(MsgUnjail)

MsgProtoNodeStake = _reflection.GeneratedProtocolMessageType('MsgProtoNodeStake', (_message.Message,), {
  'DESCRIPTOR' : _MSGPROTONODESTAKE,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.MsgProtoNodeStake)
  })
_sym_db.RegisterMessage(MsgProtoNodeStake)

MsgBeginNodeUnstake = _reflection.GeneratedProtocolMessageType('MsgBeginNodeUnstake', (_message.Message,), {
  'DESCRIPTOR' : _MSGBEGINNODEUNSTAKE,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.MsgBeginNodeUnstake)
  })
_sym_db.RegisterMessage(MsgBeginNodeUnstake)

MsgNodeUnjail = _reflection.GeneratedProtocolMessageType('MsgNodeUnjail', (_message.Message,), {
  'DESCRIPTOR' : _MSGNODEUNJAIL,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.MsgNodeUnjail)
  })
_sym_db.RegisterMessage(MsgNodeUnjail)

MsgSend = _reflection.GeneratedProtocolMessageType('MsgSend', (_message.Message,), {
  'DESCRIPTOR' : _MSGSEND,
  '__module__' : 'tx_signer_pb2'
  # @@protoc_insertion_point(class_scope:PocketWalletQt.MsgSend)
  })
_sym_db.RegisterMessage(MsgSend)


# @@protoc_insertion_point(module_scope)
